# Generated by Django 2.2.1 on 2019-05-14 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathroom', models.DecimalField(decimal_places=1, max_digits=2)),
                ('title', models.CharField(max_length=200)),
                ('garage', models.IntegerField(default=0)),
                ('sqlt', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photos_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photos_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photos_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photos_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photos_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photos_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photos_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
